-- SQL script for inserting data to the Database

insert into Groups (Name, Year, DepartmentId) values ('SPD-115', 4, 16);
insert into Groups (Name, Year, DepartmentId) values ('SBU-331', 3, 14);
insert into Groups (Name, Year, DepartmentId) values ('SPU-123', 4, 19);
insert into Groups (Name, Year, DepartmentId) values ('PV-125', 5, 4);
insert into Groups (Name, Year, DepartmentId) values ('PD-221', 1, 6);
insert into Groups (Name, Year, DepartmentId) values ('VPD-121', 2, 1);
insert into Groups (Name, Year, DepartmentId) values ('SPU-013', 1, 8);
insert into Groups (Name, Year, DepartmentId) values ('VPD-011', 5, 18);
insert into Groups (Name, Year, DepartmentId) values ('PD-014', 4, 16);
insert into Groups (Name, Year, DepartmentId) values ('KI-21', 1, 5);
insert into Groups (Name, Year, DepartmentId) values ('QA-25', 2, 19);
insert into Groups (Name, Year, DepartmentId) values ('QA-22', 3, 4);
insert into Groups (Name, Year, DepartmentId) values ('KFA-212', 2, 7);
insert into Groups (Name, Year, DepartmentId) values ('LCA-117', 4, 18);
insert into Groups (Name, Year, DepartmentId) values ('SAP-567', 4, 3);
insert into Groups (Name, Year, DepartmentId) values ('USP-007', 4, 15);
insert into Groups (Name, Year, DepartmentId) values ('ROI-097', 5, 9);
insert into Groups (Name, Year, DepartmentId) values ('BU-228', 2, 20);
insert into Groups (Name, Year, DepartmentId) values ('JEI-113', 3, 5);
insert into Groups (Name, Year, DepartmentId) values ('KOI-232', 4, 17);

insert into GroupsLectures (GroupId, LectureId) values (5, 20);
insert into GroupsLectures (GroupId, LectureId) values (16, 13);
insert into GroupsLectures (GroupId, LectureId) values (17, 15);
insert into GroupsLectures (GroupId, LectureId) values (9, 14);
insert into GroupsLectures (GroupId, LectureId) values (19, 13);
insert into GroupsLectures (GroupId, LectureId) values (9, 12);
insert into GroupsLectures (GroupId, LectureId) values (19, 12);
insert into GroupsLectures (GroupId, LectureId) values (3, 14);
insert into GroupsLectures (GroupId, LectureId) values (15, 18);
insert into GroupsLectures (GroupId, LectureId) values (17, 15);
insert into GroupsLectures (GroupId, LectureId) values (5, 13);
insert into GroupsLectures (GroupId, LectureId) values (5, 1);
insert into GroupsLectures (GroupId, LectureId) values (2, 4);
insert into GroupsLectures (GroupId, LectureId) values (16, 1);
insert into GroupsLectures (GroupId, LectureId) values (11, 10);
insert into GroupsLectures (GroupId, LectureId) values (9, 10);
insert into GroupsLectures (GroupId, LectureId) values (7, 20);
insert into GroupsLectures (GroupId, LectureId) values (18, 11);
insert into GroupsLectures (GroupId, LectureId) values (13, 1);
insert into GroupsLectures (GroupId, LectureId) values (19, 7);